version: '3.1'

volumes:
  mysql_data:
      driver: local


services:
  web-forms-ui:
    build: ./frontend/.  
    ports:
      - 8081:8080
  web-forms-api:
    build: ./backend/.  
    ports:
      - 8082:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/formsfactory?authSource=admin&retryWrites=true&w=majority
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: formsconfig

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/