/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FormValue } from './FormValue';
import {
    FormValueFromJSON,
    FormValueFromJSONTyped,
    FormValueToJSON,
} from './FormValue';

/**
 * 
 * @export
 * @interface FormSubmit
 */
export interface FormSubmit {
    /**
     * 
     * @type {string}
     * @memberof FormSubmit
     */
    formId: string;
    /**
     * 
     * @type {string}
     * @memberof FormSubmit
     */
    createdDate?: string;
    /**
     * 
     * @type {Array<FormValue>}
     * @memberof FormSubmit
     */
    values: Array<FormValue>;
}

/**
 * Check if a given object implements the FormSubmit interface.
 */
export function instanceOfFormSubmit(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "formId" in value;
    isInstance = isInstance && "values" in value;

    return isInstance;
}

export function FormSubmitFromJSON(json: any): FormSubmit {
    return FormSubmitFromJSONTyped(json, false);
}

export function FormSubmitFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormSubmit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formId': json['formId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : json['createdDate'],
        'values': ((json['values'] as Array<any>).map(FormValueFromJSON)),
    };
}

export function FormSubmitToJSON(value?: FormSubmit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'formId': value.formId,
        'createdDate': value.createdDate,
        'values': ((value.values as Array<any>).map(FormValueToJSON)),
    };
}

