/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface I18NString
 */
export interface I18NString {
    /**
     * 
     * @type {string}
     * @memberof I18NString
     */
    EN?: string;
    /**
     * 
     * @type {string}
     * @memberof I18NString
     */
    FR?: string;
}

/**
 * Check if a given object implements the I18NString interface.
 */
export function instanceOfI18NString(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function I18NStringFromJSON(json: any): I18NString {
    return I18NStringFromJSONTyped(json, false);
}

export function I18NStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): I18NString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'EN': !exists(json, 'EN') ? undefined : json['EN'],
        'FR': !exists(json, 'FR') ? undefined : json['FR'],
    };
}

export function I18NStringToJSON(value?: I18NString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EN': value.EN,
        'FR': value.FR,
    };
}

