/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InputDateConfig
 */
export interface InputDateConfig {
    /**
     * regex que la date doit respecter
     * @type {string}
     * @memberof InputDateConfig
     */
    regex?: string;
}

/**
 * Check if a given object implements the InputDateConfig interface.
 */
export function instanceOfInputDateConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InputDateConfigFromJSON(json: any): InputDateConfig {
    return InputDateConfigFromJSONTyped(json, false);
}

export function InputDateConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputDateConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regex': !exists(json, 'regex') ? undefined : json['regex'],
    };
}

export function InputDateConfigToJSON(value?: InputDateConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regex': value.regex,
    };
}

