/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InputAddressConfig
 */
export interface InputAddressConfig {
    /**
     * Description de la propriété 1
     * @type {string}
     * @memberof InputAddressConfig
     */
    min?: string;
    /**
     * Description de la propriété 1
     * @type {boolean}
     * @memberof InputAddressConfig
     */
    cp?: boolean;
    /**
     * Description de la propriété 1
     * @type {number}
     * @memberof InputAddressConfig
     */
    max?: number;
}

/**
 * Check if a given object implements the InputAddressConfig interface.
 */
export function instanceOfInputAddressConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InputAddressConfigFromJSON(json: any): InputAddressConfig {
    return InputAddressConfigFromJSONTyped(json, false);
}

export function InputAddressConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputAddressConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'min': !exists(json, 'min') ? undefined : json['min'],
        'cp': !exists(json, 'cp') ? undefined : json['cp'],
        'max': !exists(json, 'max') ? undefined : json['max'],
    };
}

export function InputAddressConfigToJSON(value?: InputAddressConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'min': value.min,
        'cp': value.cp,
        'max': value.max,
    };
}

