/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Router
 */
export interface Router {
    /**
     * 
     * @type {string}
     * @memberof Router
     */
    routerClass: string;
    /**
     * 
     * @type {object}
     * @memberof Router
     */
    routerConfig: object;
}

/**
 * Check if a given object implements the Router interface.
 */
export function instanceOfRouter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "routerClass" in value;
    isInstance = isInstance && "routerConfig" in value;

    return isInstance;
}

export function RouterFromJSON(json: any): Router {
    return RouterFromJSONTyped(json, false);
}

export function RouterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Router {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'routerClass': json['routerClass'],
        'routerConfig': json['routerConfig'],
    };
}

export function RouterToJSON(value?: Router | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'routerClass': value.routerClass,
        'routerConfig': value.routerConfig,
    };
}

