/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ff.server.api;

import ff.server.model.Account;
import ff.server.model.CreateAccountRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import javax.annotation.Generated;

@Validated
public interface AccountsApi {

    default AccountsApiDelegate getDelegate() {
        return new AccountsApiDelegate() {};
    }



    @RequestMapping(
        method = RequestMethod.POST,
        value = "/accounts",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Account> createAccount(@Valid @RequestBody(required = false) CreateAccountRequest createAccountRequest) throws Exception {
        return getDelegate().createAccount(createAccountRequest);
    }


    /**
     * GET /accounts : Create a account
     *
     * @return Requestion created (status code 200)
     */

    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Account>> listAccounts(
        
    ) throws Exception {
        return getDelegate().listAccounts();
    }

}
