/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package webforms.server.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import webforms.server.model.Account;
import webforms.server.model.CreateAccountRequest;

import javax.validation.Valid;
import java.util.List;

@Validated
public interface AccountsApi {

    default AccountsApiDelegate getDelegate() {
        return new AccountsApiDelegate() {
        };
    }


    @RequestMapping(
            method = RequestMethod.POST,
            value = "/accounts",
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    default ResponseEntity<Account> createAccount(@Valid @RequestBody(required = false) CreateAccountRequest createAccountRequest) throws Exception {
        return getDelegate().createAccount(createAccountRequest);
    }


    /**
     * GET /accounts : Create a account
     *
     * @return Requestion created (status code 200)
     */

    @RequestMapping(
            method = RequestMethod.GET,
            value = "/accounts",
            produces = {"application/json"}
    )
    default ResponseEntity<List<Account>> listAccounts(

    ) throws Exception {
        return getDelegate().listAccounts();
    }

}
