/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package webforms.server.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import webforms.server.model.FormValue;

import javax.annotation.Generated;
import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-09-30T08:28:17.528094700+02:00[Europe/Paris]")
@Validated
public interface FormResultsApi {

    default FormResultsApiDelegate getDelegate() {
        return new FormResultsApiDelegate() {
        };
    }

    /**
     * GET /formResults/{formId}
     *
     * @param formId Numeric ID of the form config (required)
     * @return List form respones with router ROUTER_DATABASE class (status code 200)
     */

    @RequestMapping(
            method = RequestMethod.GET,
            value = "/formResults/{formId}",
            produces = {"application/json"}
    )
    default ResponseEntity<List<FormValue>> listFormResults(@PathVariable("formId") String formId
    ) throws Exception {
        return getDelegate().listFormResults(formId);
    }

}
