/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FormSubmit,
} from '../models/index';
import {
    FormSubmitFromJSON,
    FormSubmitToJSON,
} from '../models/index';

export interface SubmitFormRequest {
    formSubmit?: FormSubmit;
}

/**
 * 
 */
export class FormSubmitApiControllerApi extends runtime.BaseAPI {

    /**
     */
    async submitFormRaw(requestParameters: SubmitFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormSubmit>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/formSubmit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FormSubmitToJSON(requestParameters.formSubmit),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FormSubmitFromJSON(jsonValue));
    }

    /**
     */
    async submitForm(requestParameters: SubmitFormRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormSubmit> {
        const response = await this.submitFormRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
