/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FormFieldValidation,
} from '../models/index';
import {
    FormFieldValidationFromJSON,
    FormFieldValidationToJSON,
} from '../models/index';

export interface ValidateFieldRequest {
    formFieldValidation?: FormFieldValidation;
}

/**
 * 
 */
export class ValidateApiControllerApi extends runtime.BaseAPI {

    /**
     */
    async validateFieldRaw(requestParameters: ValidateFieldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormFieldValidation>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FormFieldValidationToJSON(requestParameters.formFieldValidation),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FormFieldValidationFromJSON(jsonValue));
    }

    /**
     */
    async validateField(requestParameters: ValidateFieldRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormFieldValidation> {
        const response = await this.validateFieldRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
