name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image backend
        run: |
          docker build -t pierremellet/web-forms-api:latest ./backend
          docker push pierremellet/web-forms-api:latest

      - name: Build and push Docker image frontend
        run: |
          docker build -t pierremellet/web-forms-ui:latest ./frontend
          docker push pierremellet/web-forms-ui:latest